<?php

namespace Database\Seeders;

use App\Models\Application;
use Illuminate\Database\Seeder;
use Illuminate\Support\Carbon;

class ApplicationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $applications = [
            // Volunteer Applications
            [
                'first_name' => 'John',
                'last_name' => 'Doe',
                'email' => 'john.doe@example.com',
                'phone' => '+1234567890',
                'application_type' => 'volunteer',
                'status' => 'pending',
                'nationality' => 'American',
                'date_of_birth' => Carbon::parse('1995-05-15'),
                'address_line_1' => '123 Main Street',
                'address_line_2' => 'Apt 4B',
                'city' => 'New York',
                'state' => 'NY',
                'zip_code' => '10001',
                'country' => 'United States',
                'education_level' => 'Bachelor\'s Degree',
                'program_major' => 'Social Work',
                'languages' => 'English, Spanish',
                'available_days' => ['Monday', 'Wednesday', 'Friday'],
                'available_times' => ['Morning', 'Afternoon'],
                'interests' => ['Education', 'Community Outreach', 'Youth Programs'],
                'skills_experience' => '5 years of experience in community organizing and youth mentorship programs.',
                'motivation' => 'I am passionate about making a positive impact in my community and helping those in need.',
                'emergency_name' => 'Jane Doe',
                'emergency_relationship' => 'Spouse',
                'emergency_phone' => '+1234567891',
                'reference_name' => 'Dr. Smith',
                'reference_contact' => 'dr.smith@university.edu',
                'has_medical_condition' => false,
                'agrees_to_terms' => true,
            ],
            [
                'first_name' => 'Sarah',
                'last_name' => 'Johnson',
                'email' => 'sarah.johnson@example.com',
                'phone' => '+1234567892',
                'application_type' => 'volunteer',
                'status' => 'approved',
                'nationality' => 'Canadian',
                'date_of_birth' => Carbon::parse('1992-08-20'),
                'address_line_1' => '456 Oak Avenue',
                'city' => 'Toronto',
                'state' => 'Ontario',
                'zip_code' => 'M5H 2N2',
                'country' => 'Canada',
                'education_level' => 'Master\'s Degree',
                'program_major' => 'Public Health',
                'languages' => 'English, French',
                'available_days' => ['Saturday', 'Sunday'],
                'available_times' => ['Morning'],
                'interests' => ['Healthcare', 'Public Health', 'Community Wellness'],
                'skills_experience' => 'Extensive background in public health initiatives and community health programs.',
                'motivation' => 'I want to contribute my public health expertise to help improve community wellness.',
                'emergency_name' => 'Michael Johnson',
                'emergency_relationship' => 'Brother',
                'emergency_phone' => '+1234567893',
                'reference_name' => 'Prof. Brown',
                'reference_contact' => 'prof.brown@university.ca',
                'has_medical_condition' => false,
                'agrees_to_terms' => true,
                'admin_notes' => 'Excellent candidate, approved for volunteer position.',
            ],
            [
                'first_name' => 'Michael',
                'last_name' => 'Chen',
                'email' => 'michael.chen@example.com',
                'phone' => '+1234567894',
                'application_type' => 'volunteer',
                'status' => 'rejected',
                'nationality' => 'Chinese',
                'date_of_birth' => Carbon::parse('1998-03-10'),
                'address_line_1' => '789 Pine Street',
                'city' => 'Los Angeles',
                'state' => 'CA',
                'zip_code' => '90001',
                'country' => 'United States',
                'education_level' => 'High School Diploma',
                'program_major' => 'General Studies',
                'languages' => 'English, Mandarin',
                'available_days' => ['Tuesday', 'Thursday'],
                'available_times' => ['Evening'],
                'interests' => ['Technology', 'Education'],
                'skills_experience' => 'Basic computer skills and some tutoring experience.',
                'motivation' => 'Looking to gain experience in community service.',
                'emergency_name' => 'Li Chen',
                'emergency_relationship' => 'Parent',
                'emergency_phone' => '+1234567895',
                'reference_name' => 'Ms. Wang',
                'reference_contact' => 'ms.wang@school.edu',
                'has_medical_condition' => false,
                'agrees_to_terms' => true,
                'admin_notes' => 'Insufficient experience for current volunteer needs.',
            ],
            // Intern Applications
            [
                'first_name' => 'Emily',
                'last_name' => 'Williams',
                'email' => 'emily.williams@example.com',
                'phone' => '+1234567896',
                'application_type' => 'intern',
                'status' => 'pending',
                'nationality' => 'British',
                'date_of_birth' => Carbon::parse('2000-11-25'),
                'address_line_1' => '321 Elm Street',
                'city' => 'London',
                'state' => 'Greater London',
                'zip_code' => 'SW1A 1AA',
                'country' => 'United Kingdom',
                'education_level' => 'Currently Enrolled',
                'program_major' => 'International Relations',
                'languages' => 'English, French, German',
                'available_days' => ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
                'available_times' => ['Morning', 'Afternoon'],
                'interests' => ['International Development', 'Non-profit Management', 'Policy'],
                'skills_experience' => 'Currently studying international relations with focus on development work.',
                'motivation' => 'Seeking internship opportunity to gain hands-on experience in non-profit sector.',
                'emergency_name' => 'Robert Williams',
                'emergency_relationship' => 'Father',
                'emergency_phone' => '+1234567897',
                'reference_name' => 'Dr. Taylor',
                'reference_contact' => 'dr.taylor@university.ac.uk',
                'has_medical_condition' => false,
                'agrees_to_terms' => true,
            ],
            [
                'first_name' => 'David',
                'last_name' => 'Martinez',
                'email' => 'david.martinez@example.com',
                'phone' => '+1234567898',
                'application_type' => 'intern',
                'status' => 'approved',
                'nationality' => 'Mexican',
                'date_of_birth' => Carbon::parse('1999-07-12'),
                'address_line_1' => '654 Maple Drive',
                'city' => 'Mexico City',
                'state' => 'CDMX',
                'zip_code' => '01000',
                'country' => 'Mexico',
                'education_level' => 'Bachelor\'s Degree',
                'program_major' => 'Social Sciences',
                'languages' => 'Spanish, English',
                'available_days' => ['Monday', 'Wednesday', 'Friday'],
                'available_times' => ['Afternoon'],
                'interests' => ['Social Work', 'Community Development', 'Education'],
                'skills_experience' => 'Bachelor\'s in Social Sciences with volunteer experience in community centers.',
                'motivation' => 'Want to apply my academic knowledge in a real-world setting and contribute to meaningful projects.',
                'emergency_name' => 'Maria Martinez',
                'emergency_relationship' => 'Mother',
                'emergency_phone' => '+1234567899',
                'reference_name' => 'Prof. Garcia',
                'reference_contact' => 'prof.garcia@university.mx',
                'has_medical_condition' => false,
                'agrees_to_terms' => true,
                'admin_notes' => 'Strong candidate, approved for internship program.',
            ],
            [
                'first_name' => 'Lisa',
                'last_name' => 'Anderson',
                'email' => 'lisa.anderson@example.com',
                'phone' => '+1234567900',
                'application_type' => 'intern',
                'status' => 'pending',
                'nationality' => 'Australian',
                'date_of_birth' => Carbon::parse('2001-02-28'),
                'address_line_1' => '987 Cedar Lane',
                'city' => 'Sydney',
                'state' => 'NSW',
                'zip_code' => '2000',
                'country' => 'Australia',
                'education_level' => 'Currently Enrolled',
                'program_major' => 'Psychology',
                'languages' => 'English',
                'available_days' => ['Saturday', 'Sunday'],
                'available_times' => ['Morning', 'Afternoon'],
                'interests' => ['Mental Health', 'Counseling', 'Youth Support'],
                'skills_experience' => 'Psychology student with interest in mental health support services.',
                'motivation' => 'Looking to gain practical experience in mental health and counseling services.',
                'emergency_name' => 'James Anderson',
                'emergency_relationship' => 'Brother',
                'emergency_phone' => '+1234567901',
                'reference_name' => 'Dr. White',
                'reference_contact' => 'dr.white@university.edu.au',
                'has_medical_condition' => false,
                'agrees_to_terms' => true,
            ],
        ];

        foreach ($applications as $application) {
            Application::firstOrCreate(
                ['email' => $application['email']],
                $application
            );
        }
    }
}

